name=DevaTimer
version=1.0.0
author=Deva DIY
maintainer=Deva DIY <support@devadiy.com>
sentence=Simple non-blocking timer library for Arduino and ESP32.
paragraph=DevaTimer helps manage interval and timeout tasks without delay(). Great for ESP32, Arduino, IoT, Smart Farm, and beginner-friendly maker projects.
category=Timing
url=https://devadiy.com
architectures=*
includes=DevaTimer.h